### ISSUE TITLE
How to log?

### ISSUE THREAD

**Issue by Hidayathamir** [erajayatech/go-eraspacelog#6]
[How To Use](https://github.com/erajayatech/go-eraspacelog#how-to-use) does not show how to log.

I tried but got this panic.

![image](https://github.com/erajayatech/go-eraspacelog/assets/57469556/7ed0a635-cf94-4390-99eb-133324b10560)

**Comment by septiansahnuraziz** [comment]
> [How To Use](https://github.com/erajayatech/go-eraspacelog#how-to-use) does not show how to log.
> 
> I tried but got this panic.
> 
> ![image](https://user-images.githubusercontent.com/57469556/284816900-7ed0a635-cf94-4390-99eb-133324b10560.png)

@Hidayathamir  please try to define some variables with the value  `eraspacelog.WithContext()`, for example:
![image](https://github.com/erajayatech/go-eraspacelog/assets/18677785/5b990932-b0dd-4fd8-a07f-324516b51803)
